# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79e6b7747e3b73c3de8850d78473b90c3d8c8e1177edc7491cdb5d8503a6c6734ca88677f8a3df67b08a47d36e01273c7bc5159c9cf0712069ddca36b53c4b2

test:
  secret_key_base: 55c14cb90c36acd4d3778d639096628fbbc92235c43faed1f81ba45da6da25761f3673e133426464322d81e4551c2766fab23f7fdc02c4d027fed045357138b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
